### ISSUE TITLE
Missing crypto dependency

### ISSUE THREAD

**Issue by slavafomin** [cryptocoinjs/scryptsy#15]
Hello!

In your code you are importing the `crypto` package, however, you doesn't specify it as a dependency in your package manifest.

It should be added to the dependencies or a peer dependencies.

**Comment by junderw** [comment]
crypto is a standard NodeJS library.

**Comment by slavafomin** [comment]
That's weird, I'm sure the compiler was giving me an error in a transient dependencies regarding this import. Disregard it then.
