### ISSUE TITLE
Incorrect changelog

### ISSUE THREAD

**Issue by RyanZim** [cryptocoinjs/scryptsy#16]
https://github.com/cryptocoinjs/scryptsy/pull/13 proposed breaking changes, which were later made non-breaking, and published in 2.1.0. However, it still contained the old CHANGELOG for 3.0.0, which was merged to `master`, despite the fact there is no v3.0.0: https://github.com/cryptocoinjs/scryptsy/blob/1e9b4eb/CHANGELOG.md#300--2019-03-12

**Comment by RyanZim** [comment]
@junderw Do you want to replace this with the release notes for 2.1.0, or shall I?

**Comment by junderw** [comment]
oops!

Thanks! If you could do it I'll merge.
